#!/usr/bin/env bash

# Symbolic link with .dotfiles to ~/$HOME directory
find "$(pwd)" -name ".*" -type f -maxdepth 1 | xargs -I '{}' ln -s '{}' ~

# Ignore system/zcustom.sh file. http://stackoverflow.com/a/653495/462015
git update-index --skip-worktree system/zcustom.sh


# Install formulas
brew install autossh
brew install bash-completion@2
brew install bat
brew install diff-so-fancy
brew install docker docker-machine docker-compose
brew install elixir
brew install fzf
brew install git
brew install go
brew install grip
brew install hr
brew install htop-osx
brew install httpie
brew install jq
brew install kubectl
brew install leiningen
brew install mobile-shell
brew install nmap
brew install pstree
brew install rbenv ruby-build
brew install shellcheck
brew install the_silver_searcher
brew install tmux
brew install tree
brew install webkit2png
brew install wget
brew install wifi-password


# Install my own formulas
brew tap arturoherrero/formulae
brew install gvar


# Brew GUI Mac applications
brew install --cask appcleaner
brew install --cask authy
brew install --cask bettertouchtool
brew install --cask bitbar
brew install --cask calibre
brew install --cask cloud
brew install --cask coconutbattery
brew install --cask cyberduck
brew install --cask dash
brew install --cask db-browser-for-sqlite
brew install --cask disk-inventory-x
brew install --cask docker
brew install --cask dropbox
brew install --cask epic-games
brew install --cask evernote
brew install --cask firefox
brew install --cask fromscratch
brew install --cask google-chrome
brew install --cask google-drive
brew install --cask hiddenbar
brew install --cask imageoptim
brew install --cask intellij-idea-ce
brew install --cask iterm2
brew install --cask java
brew install --cask jdownloader
brew install --cask kap
brew install --cask karabiner-elements
brew install --cask keepingyouawake
brew install --cask kodi
brew install --cask lunar
brew install --cask macdown
brew install --cask minikube
brew install --cask openemu
brew install --cask postman
brew install --cask psequel
brew install --cask raycast
brew install --cask robomongo
brew install --cask sequel-pro
brew install --cask skype
brew install --cask slack
brew install --cask sourcetree
brew install --cask spotifree
brew install --cask spotify
brew install --cask steam
brew install --cask telegram-desktop
brew install --cask the-unarchiver
brew install --cask tomighty
brew install --cask tor-browser
brew install --cask vagrant
brew install --cask vagrant-manager
brew install --cask virtualbox
brew install --cask visual-studio-code
brew install --cask vlc
brew install --cask webtorrent
brew install --cask whatsapp


# Install MacVim & configuration
brew install macvim

git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
mvim +PluginInstall +qall
mkdir ~/.vim/undodir

defaults write -app MacVim NSUserKeyEquivalents '{
  "Show Next Tab"="~@\Uf703";
  "Show Previous Tab"="~@\Uf702";
}'


# iTerm2: Install Shell Integration
curl -L https://iterm2.com/shell_integration/install_shell_integration.sh | bash


# Update Bash version
brew install bash
sudo bash -c "echo $(brew --prefix)/bin/bash >> /etc/shells"
chsh -s "$(brew --prefix)"/bin/bash


# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable creation of metadata files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable creation of metadata files on USB volumes
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Change screenshots format
defaults write com.apple.screencapture type jpg

# Require password immediately after sleep or screen saver begins
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Show battery life percentage.
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false


# Dock

# Don’t automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# Add Documents folder to the Documents side of the Dock.
defaults write com.apple.dock persistent-others -array-add "\
<dict>\
  <key>tile-data</key>\
    <dict>\
      <key>file-data</key>\
        <dict>\
          <key>_CFURLString</key> <string>file:///Users/arturo/Documents/</string>\
          <key>_CFURLStringType</key> <integer>15</integer>\
        </dict>\

      <key>file-type</key> <integer>2</integer>\
      <key>showas</key> <integer>1</integer>\
    </dict>\

  <key>tile-type</key> <string>directory-tile</string>\
</dict>"

# Remove items located on the Applications side of the Dock.
defaults write com.apple.dock persistent-apps -array

# Automatically hide the dock.
defaults write com.apple.dock autohide -bool true

# Don't show recent items.
defaults write com.apple.dock show-recents -bool false

killall Dock


# Install all available software updates
sudo softwareupdate -ia
