#!/usr/bin/env bash

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"

# Install formulas
brew install ack
brew install autossh
brew install bash
brew install git
brew install htop-osx
brew install hr
brew install hub
brew install macvim
brew install pstree
brew install rbenv ruby-build
brew install tmux
brew install tree
brew install webkit2png
brew install wget
