#!/usr/bin/env bash

# Symbolic link with .dotfiles to ~/$HOME directory
find "$(pwd)" -name ".*" -type f -maxdepth 1 | xargs -I '{}' ln -s '{}' ~

# Ignore system/custom.sh file. http://stackoverflow.com/a/653495/462015
git update-index --skip-worktree system/custom.sh

# Install Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install formulas
brew install ack
brew install autossh
brew install docker docker-machine docker-compose
brew install git
brew install homebrew/versions/bash-completion2
brew install hr
brew install htop-osx
brew install httpie
brew install hub
brew install macvim
brew install mobile-shell
brew install nmap
brew install pstree
brew install rbenv ruby-build
brew install tmux
brew install tree
brew install webkit2png
brew install wget

# Install Python packages
sudo easy_install Pygments

# Vim plugin manager
git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
mvim +PluginInstall +qall

# Brew GUI Mac applications
brew install caskroom/cask/brew-cask
brew cask install alfred
brew cask install bettertouchtool
brew cask install caffeine
brew cask install calibre
brew cask install chitchat
brew cask install cloud
brew cask install dropbox
brew cask install evernote
brew cask install dash
brew cask install flickr-uploadr
brew cask install gimp
brew cask install google-chrome
brew cask install imageoptim
brew cask install iterm2
brew cask install jdownloader
brew cask install kodi
brew cask install macdown
brew cask install macvim
brew cask install openemu
brew cask install osxfuse
brew cask install psequel
brew cask install robomongo
brew cask install sequel-pro
brew cask install skype
brew cask install slack
brew cask install sourcetree
brew cask install spotifree
brew cask install spotify
brew cask install sqlitebrowser
brew cask install the-unarchiver
brew cask install tomighty
brew cask install vagrant
brew cask install vagrant-manager
brew cask install virtualbox
brew cask install vlc

# Bash 4 in OS X
brew install bash
sudo echo $(brew --prefix)/bin/bash >> /etc/shells
chsh -s $(brew --prefix)/bin/bash

# Prevent Time Machine from prompting to use new hard drives as backup volume
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

# Disable creation of metadata files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable creation of metadata files on USB volumes
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Change screenshots format
defaults write com.apple.screencapture type jpg

# Install all available software updates
sudo softwareupdate -ia
